//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AHVMigration) DeepCopyInto(out *AHVMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AHVMigration.
func (in *AHVMigration) DeepCopy() *AHVMigration {
	if in == nil {
		return nil
	}
	out := new(AHVMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AHVMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AHVMigrationList) DeepCopyInto(out *AHVMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AHVMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AHVMigrationList.
func (in *AHVMigrationList) DeepCopy() *AHVMigrationList {
	if in == nil {
		return nil
	}
	out := new(AHVMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AHVMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AHVMigrationSpec) DeepCopyInto(out *AHVMigrationSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.VMs != nil {
		in, out := &in.VMs, &out.VMs
		*out = make([]VMSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkMappings != nil {
		in, out := &in.NetworkMappings, &out.NetworkMappings
		*out = make([]NetworkMapping, len(*in))
		copy(*out, *in)
	}
	if in.StorageMappings != nil {
		in, out := &in.StorageMappings, &out.StorageMappings
		*out = make([]StorageMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AHVMigrationSpec.
func (in *AHVMigrationSpec) DeepCopy() *AHVMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(AHVMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AHVMigrationStatus) DeepCopyInto(out *AHVMigrationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.VMs != nil {
		in, out := &in.VMs, &out.VMs
		*out = make([]VMStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AHVMigrationStatus.
func (in *AHVMigrationStatus) DeepCopy() *AHVMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(AHVMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AHVSourceSpec) DeepCopyInto(out *AHVSourceSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.PESecretRef != nil {
		in, out := &in.PESecretRef, &out.PESecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.WarmFinalFullSync != nil {
		in, out := &in.WarmFinalFullSync, &out.WarmFinalFullSync
		*out = new(bool)
		**out = **in
	}
	if in.CBT != nil {
		in, out := &in.CBT, &out.CBT
		*out = new(CBTConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AHVSourceSpec.
func (in *AHVSourceSpec) DeepCopy() *AHVSourceSpec {
	if in == nil {
		return nil
	}
	out := new(AHVSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBTConfig) DeepCopyInto(out *CBTConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBTConfig.
func (in *CBTConfig) DeepCopy() *CBTConfig {
	if in == nil {
		return nil
	}
	out := new(CBTConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestPrepSSHConfig) DeepCopyInto(out *GuestPrepSSHConfig) {
	*out = *in
	out.SSHSecretRef = in.SSHSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestPrepSSHConfig.
func (in *GuestPrepSSHConfig) DeepCopy() *GuestPrepSSHConfig {
	if in == nil {
		return nil
	}
	out := new(GuestPrepSSHConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestPrepWinRMConfig) DeepCopyInto(out *GuestPrepWinRMConfig) {
	*out = *in
	out.WinRMSecretRef = in.WinRMSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestPrepWinRMConfig.
func (in *GuestPrepWinRMConfig) DeepCopy() *GuestPrepWinRMConfig {
	if in == nil {
		return nil
	}
	out := new(GuestPrepWinRMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkMapping) DeepCopyInto(out *NetworkMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkMapping.
func (in *NetworkMapping) DeepCopy() *NetworkMapping {
	if in == nil {
		return nil
	}
	out := new(NetworkMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageMapping) DeepCopyInto(out *StorageMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageMapping.
func (in *StorageMapping) DeepCopy() *StorageMapping {
	if in == nil {
		return nil
	}
	out := new(StorageMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMSpec) DeepCopyInto(out *VMSpec) {
	*out = *in
	if in.GuestPrepConfig != nil {
		in, out := &in.GuestPrepConfig, &out.GuestPrepConfig
		*out = new(GuestPrepSSHConfig)
		**out = **in
	}
	if in.GuestPrepWinRMConfig != nil {
		in, out := &in.GuestPrepWinRMConfig, &out.GuestPrepWinRMConfig
		*out = new(GuestPrepWinRMConfig)
		**out = **in
	}
	if in.UEFI != nil {
		in, out := &in.UEFI, &out.UEFI
		*out = new(bool)
		**out = **in
	}
	if in.KeepMAC != nil {
		in, out := &in.KeepMAC, &out.KeepMAC
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMSpec.
func (in *VMSpec) DeepCopy() *VMSpec {
	if in == nil {
		return nil
	}
	out := new(VMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMStatus) DeepCopyInto(out *VMStatus) {
	*out = *in
	if in.DataVolumeRefs != nil {
		in, out := &in.DataVolumeRefs, &out.DataVolumeRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TempImageRefs != nil {
		in, out := &in.TempImageRefs, &out.TempImageRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SnapshotPaths != nil {
		in, out := &in.SnapshotPaths, &out.SnapshotPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SyncJobRefs != nil {
		in, out := &in.SyncJobRefs, &out.SyncJobRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PendingSnapshotPaths != nil {
		in, out := &in.PendingSnapshotPaths, &out.PendingSnapshotPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeltaImageRefs != nil {
		in, out := &in.DeltaImageRefs, &out.DeltaImageRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMStatus.
func (in *VMStatus) DeepCopy() *VMStatus {
	if in == nil {
		return nil
	}
	out := new(VMStatus)
	in.DeepCopyInto(out)
	return out
}
